# Generated by Django 5.1.1 on 2026-05-06 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACLSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('witnessed', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('paused', 'Paused')], db_index=True, default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('actions', models.JSONField(default=list)),
                ('elapsed_time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ACLSMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('administered_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='acls.aclssession')),
            ],
            options={
                'ordering': ['administered_time'],
            },
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['user', 'start_time'], name='acls_aclsse_user_id_699b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['user', 'end_time'], name='acls_aclsse_user_id_16dc05_idx'),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['user', 'status'], name='acls_aclsse_user_id_278eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['status', 'start_time'], name='acls_aclsse_status_a38dee_idx'),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['status'], name='acls_aclsse_status_090930_idx'),
        ),
        migrations.AddIndex(
            model_name='aclsmedication',
            index=models.Index(fields=['session', 'medication'], name='acls_aclsme_session_cec2da_idx'),
        ),
        migrations.AddIndex(
            model_name='aclsmedication',
            index=models.Index(fields=['administered_time'], name='acls_aclsme_adminis_7fb514_idx'),
        ),
    ]
