# Generated by Django 5.1.1 on 2026-04-15 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0002_acls_medication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aclssession',
            options={'ordering': ['-start_time']},
        ),
        migrations.RenameIndex(
            model_name='aclsmedication',
            new_name='acls_aclsme_session_cec2da_idx',
            old_name='acls_aclsme_session__c4b8e8_idx',
        ),
        migrations.RenameIndex(
            model_name='aclsmedication',
            new_name='acls_aclsme_adminis_7fb514_idx',
            old_name='acls_aclsme_adminis_4b8c4a_idx',
        ),
        migrations.AddField(
            model_name='aclssession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aclssession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('paused', 'Paused')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='aclssession',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aclssession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['user', 'start_time'], name='acls_aclsse_user_id_699b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['user', 'end_time'], name='acls_aclsse_user_id_16dc05_idx'),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['user', 'status'], name='acls_aclsse_user_id_278eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['status', 'start_time'], name='acls_aclsse_status_a38dee_idx'),
        ),
        migrations.AddIndex(
            model_name='aclssession',
            index=models.Index(fields=['status'], name='acls_aclsse_status_090930_idx'),
        ),
    ]
