name: acls_mobile
description: "ACLS Trainer - Emergency Medical Training App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.4.0
  connectivity_plus: ^7.1.1

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.0.0

  # Local Storage
  shared_preferences: ^2.2.3

  # Media
  video_player: ^2.8.3
  cached_network_image: ^3.3.1

  # Fonts
  google_fonts: ^6.2.1

  # Icons
  cupertino_icons: ^1.0.6

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Audio
  audioplayers: ^6.1.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^12.4.0
  flutter_tts: ^4.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFF7ED"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie/
