from .bls import BLS_WORKFLOW
from .abcde import ABCDE_WORKFLOW
from .airway_anatomy import AIRWAY_ANATOMY_WORKFLOW
from .adv_airway import ADV_AIRWAY_WORKFLOW
from .ecg import ECG_WORKFLOW
from .rhythms import RHYTHMS_WORKFLOW
from .cardiac_alg import CARDIAC_ALG_WORKFLOW
from .stroke import STROKE_WORKFLOW
from .acs import ACS_WORKFLOW
from .h5t5 import H5T5_WORKFLOW
from .poisoning import POISONING_WORKFLOW
from .disaster import DISASTER_WORKFLOW
from .snake_bite import SNAKE_BITE_WORKFLOW
from .delivery import DELIVERY_WORKFLOW
from .scene_safety import SCENE_SAFETY_WORKFLOW
from .trauma import TRAUMA_WORKFLOW
from .choking import CHOKING_WORKFLOW
from .acls_sim import ACLS_SIM_WORKFLOW

# Merge all workflows into a single dictionary
WORKFLOW_STEPS = {}
WORKFLOW_STEPS.update(BLS_WORKFLOW)
WORKFLOW_STEPS.update(ABCDE_WORKFLOW)
WORKFLOW_STEPS.update(AIRWAY_ANATOMY_WORKFLOW)
WORKFLOW_STEPS.update(ADV_AIRWAY_WORKFLOW)
WORKFLOW_STEPS.update(ECG_WORKFLOW)
WORKFLOW_STEPS.update(RHYTHMS_WORKFLOW)
WORKFLOW_STEPS.update(CARDIAC_ALG_WORKFLOW)
WORKFLOW_STEPS.update(STROKE_WORKFLOW)
WORKFLOW_STEPS.update(ACS_WORKFLOW)
WORKFLOW_STEPS.update(H5T5_WORKFLOW)
WORKFLOW_STEPS.update(POISONING_WORKFLOW)
WORKFLOW_STEPS.update(DISASTER_WORKFLOW)
WORKFLOW_STEPS.update(SNAKE_BITE_WORKFLOW)
WORKFLOW_STEPS.update(DELIVERY_WORKFLOW)
WORKFLOW_STEPS.update(SCENE_SAFETY_WORKFLOW)
WORKFLOW_STEPS.update(TRAUMA_WORKFLOW)
WORKFLOW_STEPS.update(CHOKING_WORKFLOW)
WORKFLOW_STEPS.update(ACLS_SIM_WORKFLOW)
